### ISSUE TITLE
Input order of @context and +project

### ISSUE THREAD

**Issue by chad-betamax** [Fanteria/todotxt-tui#25]
Could there be an option to switch the order of input

Current behaviour for input is

```
dummy task @mycontext +myproject
```

whereas I want to do 

```
@mycontext +myproject dummy task
```

as I find I think about the task in a descending order

**Comment by Fanteria** [comment]
This is definitely a bug. Thank you for reporting it. Currently, the function that colors projects, contexts, and hashtags expects them to be followed only by specific key/value tags.

**Comment by Fanteria** [comment]
It should now be fixed in the `master` branch and in tag `v0.2.2`. Additionally, you can customize how tasks are displayed. For more details, check the [documentation](https://fanteria.github.io/todotxt-tui/configuration/widget/list.html).

**Comment by chad-betamax** [comment]
First pass of using - seems to work (haven't fully tested though).
Great, thanks!

by the way you forgot to bump your version number
```$ todotxt-tui --version
todotxt-tui 0.2.1

**Comment by Fanteria** [comment]
Thanks, I forgot to fix it after pushing the new version to crates.io. It’s fixed now.
